# Generated by Django 5.1.3 on 2024-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], max_length=20)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serialCarroceria', models.CharField(max_length=50)),
                ('serialMotor', models.CharField(max_length=50, verbose_name='Serial Motor')),
                ('categoria', models.CharField(choices=[('particular', 'Particular'), ('carga', 'Carga'), ('transporte', 'Transporte'), ('carga', 'Carga')], max_length=20)),
                ('precio', models.IntegerField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(auto_now=True)),
            ],
        ),
    ]
