# Generated by Django 5.1.3 on 2024-12-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculo_serialcarroceria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('aadd_vehiculomodel', 'Puede agregar vehiculos')]},
        ),
    ]
