# Generated by Django 5.1.3 on 2024-12-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('add_vehiculomodel', 'Puede agregar vehiculos')]},
        ),
    ]
